### ISSUE TITLE
How to Run?

### ISSUE THREAD

**Issue by p110120p1** [itsnine/yolov5-onnxruntime#1]
Hello, thank you for doing this project. Now I have a problem. How to run the code after I compile it with Cmake
![image](https://user-images.githubusercontent.com/54127320/134813004-1f727b71-5d45-4597-be30-b035df0f719f.png)
![image](https://user-images.githubusercontent.com/54127320/134813075-88ec6907-f717-463f-9c6f-d7e02247adf3.png)

**Comment by itsnine** [comment]
@p110120p1 hello, if you have already compiled it the executable yolo_ort.exe should be located in Debug folder.

**Comment by p110120p1** [comment]
@itsnine ok..But when I tried, a new problem arose
![image](https://user-images.githubusercontent.com/54127320/134813711-b7a42631-f131-4ba0-8b9a-8f55eb4ba7f1.png)

**Comment by itsnine** [comment]
@p110120p1 I don't speak chinese, but maybe it doesn't see where the OpenCV and ONNXRuntime libraries are located, could you try to copy opencv and onnxruntime libraries near the executable? And in the args you should specify your model path, image path and classnames path

**Comment by itsnine** [comment]
@p110120p1 strange error, which Visual Studio version do you have?

**Comment by p110120p1** [comment]
@itsnine vs2019,When I changed the path and put the library in this folder, the error still exists
![image](https://user-images.githubusercontent.com/54127320/134814364-c8535e41-3ec3-498e-99ca-a1398c928c3b.png)

**Comment by itsnine** [comment]
@p110120p1 could you try to copy opencv_world453d.dll?

**Comment by p110120p1** [comment]
@itsnine It's the same mistake

**Comment by itsnine** [comment]
@p110120p1 did you build you onnxruntime? I don't see onnxruntime.dll in your folder, could you copy it as well?

**Comment by itsnine** [comment]
@p110120p1 And try to use first without --gpu argument.

**Comment by p110120p1** [comment]
@itsnine it's work! Once I put onnxRuntime. dll in it, it will be fine. Thanks for your help.
![image](https://user-images.githubusercontent.com/54127320/134814962-8ac6f1b8-8803-484a-a35b-63c65cc1e7a1.png)

**Comment by itsnine** [comment]
@p110120p1 I'm glad that you have done it! Actually you have to have only 2 dll's near the executable if you haven't configured your environment path, it's onnxruntime.dll and opencv_world452d.dll

**Comment by p110120p1** [comment]
@itsnine Ok, I will conduct further experiments and feel your enthusiastic help again
