### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ShakhzodbekYuldoshov** [itsnine/yolov5-onnxruntime#10]

**Comment by ShakhzodbekYuldoshov** [comment]
I did not understand wht is going on.
Wrote this line of command:
./yolo_ort --model_path best.onnx --image img.jpeg --class_names coco.names --gpu
But it is returning just this line of error there is no other error messages. What should I do? Thank you beforehand

**Comment by ShakhzodbekYuldoshov** [comment]
I found that Model is not being initialized

**Comment by ShakhzodbekYuldoshov** [comment]
env = Ort::Env(OrtLoggingLevel::ORT_LOGGING_LEVEL_WARNING, "ONNX_DETECTION");

I found one more information it cannot execute this line of code. I do not know C++ very well. So I am not understanding what is going on.

**Comment by itsnine** [comment]
@ShakhzodbekYuldoshov Which onnxruntime version do you have? Did you try to build and run without --gpu argument? Is your path to the model correct?

**Comment by ShakhzodbekYuldoshov** [comment]
@itsnine Thank you very much. I found that it was because of onnxruntime version. I used 1.6 gave an error, then tried 1.10 working fine
