### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by mifan0208** [itsnine/yolov5-onnxruntime#11]
ort:onnxruntime-linux-x64-1.10.0
download from onnxruntime-release

![image](https://user-images.githubusercontent.com/48484309/158297159-b0bda21b-ffd6-42c4-ac68-bfbbacd190f8.png)

Thanks for your replay

**Comment by itsnine** [comment]
@mifan0208 are you sure that your modelPath is correct? Did you try lower version of onnxruntime, i.e. 1.8 or 1.9?
