### ISSUE TITLE
fatal error LNK 1104

### ISSUE THREAD

**Issue by Defa6** [itsnine/yolov5-onnxruntime#13]
Hello,
I am trying to run this example, but when I'm writing "`cmake --build .`" in the terminal, I always get this error: 

```
LINK : fatal error LNK1104: Datei "onnxruntime-win-x64\onnxruntime-win-x64\lib\onnxruntime.lib.lib" kann nicht geöffnet werden. [...\build\yolo_ort.vcxproj]
```
Maybe the "lib.lib" from `onnxruntime.lib.lib` is the problem, but I don't know how to solve it.
I am using the win-x64-1.10.0 onnxruntime version.

Thanks for your help.

**Comment by itsnine** [comment]
@Defa6 hello, how did you specify the path to onnxruntime before build? I tested on windows 10 with win-x64-onnxruntime-1.10.0 and it works. I specified path to onnxruntime as follows:
`cmake .. -DONNXRUNTIME_DIR=C:/libs/onnxruntime-win-x64-1.10.0/`

**Comment by Defa6** [comment]
Ah okay, I found my mistake. I haven't use the C:/ for the path. 
Thanks :)
