### ISSUE TITLE
How to change imgsz?

### ISSUE THREAD

**Issue by p110120p1** [itsnine/yolov5-onnxruntime#2]
Hello, I had an experiment where all the images were high pixels, so scaling to 640*640 would cause the target to be too small. I tried to modify the c++ file in the src folder to change 640 to 1280, but after compiling, I still need 640 input, so how should I modify the project?

**Comment by itsnine** [comment]
@p110120p1 hello, does your onnx model have dynamic input shape?

**Comment by itsnine** [comment]
@p110120p1 I found a problem with different input shape, I'll fix it soon.

**Comment by p110120p1** [comment]
@itsnine Okay, I tried that before and it didn't work, so I'll try again. Thank you very much

**Comment by itsnine** [comment]
@p110120p1 Thank you for your feedback on this project and let me know if you have any issues.
