### ISSUE TITLE
How to find onnxruntime_cxx_api.h?

### ISSUE THREAD

**Issue by lucasjinreal** [itsnine/yolov5-onnxruntime#8]
Hi, I have built onnxruntime on macOS, but under MacOS/Release folder, there is no onnxruntime_cxx_api such file at all.
Also, there is no such lib sub folder under it, it just inside MacOS/Release/libonnxruntime.dylib.

How should I set them under macOS?

just got 2 such file in src:

```
/libs/onnxruntime//cmake/external/onnxruntime-extensions/includes/onnxruntime/onnxruntime_cxx_api.h
/libs/onnxruntime//include/onnxruntime/core/session/onnxruntime_cxx_api.h
```

**Comment by zhiqwang** [comment]
there is an example for this problem

<https://github.com/zhiqwang/yolov5-rt-stack/blob/c6131f4/deployment/onnxruntime/CMakeLists.txt#L14-L15>
<https://github.com/zhiqwang/yolov5-rt-stack/blob/c6131f4/deployment/onnxruntime/CMakeLists.txt#L26-L28>

cc @itsnine , I can make a PR for this problem if you're interested to support macOS.

**Comment by itsnine** [comment]
@zhiqwang hi, it would be great if you make a PR to support macOS devices.

**Comment by lucasjinreal** [comment]
I managed to build it. Just curiosity about why there is 2 different file with same file name (their content actually not same). The CMakelists.txt I don't have a lib under onnxruntime, it was under `onnxruntime/build/Mac/Release`.
It still need manually specific lib path and include path.

**Comment by zhiqwang** [comment]
> Just curiosity about why there is 2 different file with same file name (their content actually not same). 

Hahaha, I also feel very strange, and this question is more appropriate to ask Microsoft.
