### ISSUE TITLE
ort batch inference

### ISSUE THREAD

**Issue by shining-love** [itsnine/yolov5-onnxruntime#9]
hello,I have tested ort c++ inference successfully! but I didn't make batch inference works! could you please give a batch inference  c++ example?? 
Thank you very much!

**Comment by itsnine** [comment]
@yang-gis hello, sorry for the late answer I didn't have time for that. I did only batch=1 inference code. As a simple solution you can run the detection in `for` loop iterating over your images. In my experience, if your batch_size is small, i.e. 4, probably there won't be a significantly better performance comparing with the simple loop.
